import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'
import jwt from 'jsonwebtoken'
import styles from '@/styles/Home.module.css'

import Header from '../components/header';

export default function Login() {

  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [message, setMessage] = useState<string>('Next');
  const [secret, setSecret] = useState<string>('Next');

  async function submitForm() {
    setMessage('Loading...');
  const res = await fetch('http://localhost:3000/api/login', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      username,
      password
    })
  }).then((t) => t.json())

  const { token } = res;
  console.log(token);

  if(token) {
    localStorage.setItem('token', token);
    const json = jwt.decode(token) as { [key: string]: string}
    console.log("🚀 ~ file: index.tsx:36 ~ submitForm ~ json:", json)
    if(json.login) {
      setMessage(`Your are logged in ${json.username}`);
    } else {
      setMessage('Invalid username or password');
    }

    const res = await fetch('http://localhost:3000/api/secret', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        token
      })
    }).then((t) => t.json())

    console.log(res);
    if(res.secretAdminCode) {
      setSecret(res.secretAdminCode);
    } else{
      setMessage('Something went wrong');
    }


  } else {
    setMessage('Something went wrong');
  }
}

  return (
    <>
      <Head>
        <title>Login | Raaz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.center}>
          <Header />
       </div>
      <main className={styles.main}>
        <h1>{message}</h1>
        <h2>{secret}</h2>
        <form>
          <label htmlFor="username">Username</label>
          <input type="text" id="username" name="username" value={username} 
            onChange={(e) => setUsername(e.target.value)}/>
          <br></br>
          <label htmlFor="password">Password</label>
          <input type="password" id="password" name="password" value={password} 
            onChange={(e) => setPassword(e.target.value) } />
          <br></br>
          <input type="button" value="Login" onClick={submitForm}/>
        </form>
      </main>
    </>
  )
}
